#!/bin/bash
PKG=""
if [ "$1" = "kika" ] ; then
	PKG="com.qisiemoji.inputmethod"
elif [ "$1" = "pro" ] ; then
	PKG="com.emoji.coolkeyboard"
elif [ "$1" = "ikey" ] ; then
	PKG="com.emoji.ikeyboard"
else
	echo "Wrong Selection, run it again"
fi

#clear app data
COMMON_PREFIX_CLEAR="adb shell pm clear "
echo `$COMMON_PREFIX_CLEAR$PKG`


#push file
COMMON_PREFIX_PUSH="adb push koala_event_sampling.properties "
COMMON_MID_PUSH="/sdcard/Android/data/"
COMMON_TAIL_PUSH="/files/koala/koala_event_sampling.properties"
echo `$COMMON_PREFIX_PUSH$COMMON_MID_PUSH$PKG$COMMON_TAIL_PUSH`

